import { Request, Response } from 'express';
import { Prisma } from '@prisma/client';
import prisma from '../config/prisma'; // FIX: Correct default import
import { asyncHandler } from '../utils/asyncHandler';

export const createDocument = asyncHandler(async (req: Request, res: Response) => {
  const { title, description, priority, departmentId } = req.body;

  if (!req.user || !req.user.id) {
    return res.status(401).json({
      success: false,
      message: 'Unauthorized: Missing user authentication context.',
    });
  }

  const authenticatedUserId = req.user.id;

  if (!title || !departmentId) {
    return res.status(400).json({
      success: false,
      message: 'Validation failed: title and departmentId are required.',
    });
  }

  try {
    const result = await prisma.$transaction(async (tx) => {
      const department = await tx.department.findUnique({
        where: { id: Number(departmentId) },
      });

      if (!department) {
        throw new Error('DEPARTMENT_NOT_FOUND');
      }

      const currentYear = new Date().getFullYear();
      const startOfYear = new Date(`${currentYear}-01-01T00:00:00.000Z`);
      const endOfYear = new Date(`${currentYear}-12-31T23:59:59.999Z`);

      // Count documents in this department for the yearly sequence (uses aligned FK name)
      const documentCount = await tx.document.count({
        where: {
          currentDepartmentId: department.id,
          createdAt: {
            gte: startOfYear,
            lte: endOfYear,
          },
        },
      });

      const cleanDeptCode = department.code || department.name.substring(0, 3).toUpperCase();
      const sequenceNumber = String(documentCount + 1).padStart(4, '0');
      const trackingNumber = `SMART-${cleanDeptCode}-${currentYear}-${sequenceNumber}`;

      const document = await tx.document.create({
        data: {
          trackingNumber,
          title,
          description,
          priority: priority || 'NORMAL',
          currentDepartmentId: department.id,
          createdById: authenticatedUserId,
        },
      });

      const auditLog = await tx.auditLog.create({
        data: {
          documentId: document.id,
          userId: authenticatedUserId,
          action: 'DOCUMENT_GENERATION',
          details: `Document registered successfully. Tracking Number: ${trackingNumber}. Generated by User ID: ${authenticatedUserId}.`,
        },
      });

      return { document, auditLog };
    });

    return res.status(201).json({
      success: true,
      message: 'Document tracking initialized successfully.',
      data: result,
    });
  } catch (error: any) {
    if (error.message === 'DEPARTMENT_NOT_FOUND') {
      return res.status(404).json({
        success: false,
        message: `Department with ID ${departmentId} does not exist.`,
      });
    }

    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      return res.status(409).json({
        success: false,
        message: 'Concurrency conflict: Reference number sequence allocation failed. Please retry your request.',
      });
    }
    
    // Re-throw any other unhandled errors to let the global asyncHandler deal with it
    throw error; 
  }
});